### ISSUE TITLE
scRNA input for signature

### ISSUE THREAD

**Issue by pakiessling** [HiDiHlabs/sainsc#10]
Heya,

I am interested in trying this with my data.

How should I process the scRNA reference before calculating the signature?

Logspace? Counts? Depth normalization?

Ty!

**Comment by niklasmueboe** [comment]
Hi,

thanks for the interest in the package. 

It depends a bit on the data (as always), but as a default I think library size normalization + log transformation are a good choice. 

I think I never really tested it without library size normalization.

Regarding log-transformation;
- when analysing Xenium for example we mostly didn't notice large differences in the resulting cell type assignment when using log-transformed vs non-transformed signatures. This likely might be influenced by the fact that the choice of genes in the panel already is "biased" towards genes that are expressed in a similar range and few genes are used anyway.
- for Stereo-seq/Nova-ST we almost always used log-transformed signatures.

As a side note as well, you probably should first log-transform your data before calculating the signatures and not the other way around.

**Comment by pakiessling** [comment]
Thank you!
I think the api is much nicer than Ficture :)
Looking forward to giving it a spin

**Comment by AtlasMaroc** [comment]
@niklasmueboe @pakiessling how do i get the single cell signatures?

**Comment by niklasmueboe** [comment]
That depends on your use case.

You can use data from literature (see the sainsc publication for examples), but also your own accompanying or previous experiments.

The tutorials give some hints on how to calculate them (e.g. from the spatial data itself but the same approach applies to scRNA-seq data, https://sainsc.readthedocs.io/stable/usage.html#de-novo-cell-type-signatures)

**Comment by AtlasMaroc** [comment]
@niklasmueboe, for visium HD, if we have a reference dataset that we want to annotate the spatial data with, we use the function sainsc.utils.celltype_signatures() to extract signatures from reference. however for reference, do we apply the same pre-processing as in demo for adata_16um (normalization, log1p, high variable genes) ?

**Comment by niklasmueboe** [comment]
Generally, I recommend using a subset of the genes only; i.e. HVG/SVG or DEG from literature.

In terms of preprocessing the same that I have written [above](https://github.com/HiDiHlabs/sainsc/issues/10#issuecomment-2315175460) applies I think; for sequencing-based technologies where you have full transcriptome coverage the selection of your genes also may have a broad range of expression, I think in these cases log1p transformation is useful. If you transform the signatures I'd recommend also using log for the [celltype assignment](https://sainsc.readthedocs.io/stable/autoapi/sainsc/lazykde/LazyKDE.assign_celltype.html#sainsc.lazykde.LazyKDE.assign_celltype)

**Comment by AtlasMaroc** [comment]
@niklasmueboe thank you for the response, if the reference cells for scRNA are already annotated and anndata doesn't have a leiden representation or a cluster , can we provide the 'cell_type' key directly to the function, or we need to cluster the cells first ?

**Comment by niklasmueboe** [comment]
Yes, you can use any column in `AnnData.obs`.
