### ISSUE TITLE
Unable to Install sainsc on macOS using Mamba

### ISSUE THREAD

**Issue by rasools** [HiDiHlabs/sainsc#14]
Description:
I tried to create an environment with the sainsc package using mamba, but I received an error stating that the package does not exist, despite it being listed in Bioconda.

Steps to Reproduce:
I ran the following command to create a new environment with sainsc:

```
mamba create --name myenvname sainsc
The command resulted in the following output:
```

```
Looking for: ['sainsc']

conda-forge/osx-64                                          Using cache
conda-forge/noarch                                          Using cache
bioconda/osx-64                                             Using cache
bioconda/noarch                                             Using cache
pkgs/r/noarch                                                 No change
pkgs/r/osx-64                                                 No change
pkgs/main/osx-64                                              No change
pkgs/main/noarch                                              No change
Could not solve for environment specs
The following package could not be installed
└─ sainsc does not exist (perhaps a typo or a missing channel).
```

System Information:
`sysctl -n machdep.cpu.brand_string
`Operating System: macOS (Apple M3 Pro)
Package Manager: Mamba
```
mamba 1.5.0
conda 22.11.1
```
Conda Channels Used: bioconda, conda-forge, defaults
Python Version: 3.9 (also tested with 3.10)

Additional Context:
The [Bioconda recipe](https://bioconda.github.io/recipes/sainsc/README.html) shows that sainsc should be available. However, it appears the package cannot be found for macOS, even after ensuring that Bioconda is correctly prioritized.

Could you please check if the package is available for macOS, or provide guidance on what might be missing?

**Comment by niklasmueboe** [comment]
Hi, first of all thanks for your interest in this package.

You will need at least python 3.10 to run sainsc.

Regarding macOS, this depends a bit on the actual hardware you are running. On bioconda sainsc is only available for ARM architecture of macOS, that means the newer Apple silicon (i.e. M1 processors and after if I am not mistaken) not the older Intel processors.

If you are running macOS with an Intel chip (which is likely the case if you couldn't install using conda) there are 2 options:

- install via pip; on PyPI a compiled version of the package should be available for macOS with Intel Hardware (x86_64)
- compile from source; for that you could follow the [install guide in the documentation](https://sainsc.readthedocs.io/en/stable/installation.html#from-github). (However I would recommend the first option)
